import 'package:rewear/core/constants/enums.dart';
import 'package:rewear/data/models/item.dart';

/// Test-only Item builder with sensible defaults so each test overrides only
/// the fields under test. Defaults model a plain casual T-shirt added "now".
Item makeItem({
  String id = 'item-1',
  String userId = 'user-1',
  String name = 'Test Item',
  ItemCategory category = ItemCategory.top,
  String type = 'T_SHIRT',
  List<String> colorTags = const ['navy'],
  List<Occasion> occasionTags = const [Occasion.casual],
  int formalityLevel = 2,
  int condition = 5,
  ConditionReviewMode conditionReviewMode = ConditionReviewMode.auto,
  int? conditionNextDrop,
  bool isFavorite = false,
  ItemStatus status = ItemStatus.inWardrobe,
  DateTime? dateAdded,
  bool isNewItem = true,
  InitialHistoryType initialHistoryType = InitialHistoryType.brandNew,
  String? initialWearCountOption,
  int initialUsageAgeDays = 0,
  bool wearCountUnknown = false,
  bool lastWornUnknown = false,
  int wearCount = 0,
  DateTime? lastWornDate,
  int skipCount = 0,
  DateTime? laundryStartedAt,
  DateTime? keptUntil,
  DateTime? donatedAt,
}) {
  final added = dateAdded ?? DateTime(2026, 1, 1);
  return Item(
    id: id,
    userId: userId,
    name: name,
    category: category,
    type: type,
    colorTags: colorTags,
    occasionTags: occasionTags,
    formalityLevel: formalityLevel,
    condition: condition,
    conditionReviewMode: conditionReviewMode,
    conditionNextDrop: conditionNextDrop,
    isFavorite: isFavorite,
    status: status,
    dateAdded: added,
    isNewItem: isNewItem,
    initialHistoryType: initialHistoryType,
    initialWearCountOption: initialWearCountOption,
    initialUsageAgeDays: initialUsageAgeDays,
    wearCountUnknown: wearCountUnknown,
    lastWornUnknown: lastWornUnknown,
    wearCount: wearCount,
    lastWornDate: lastWornDate,
    skipCount: skipCount,
    laundryStartedAt: laundryStartedAt,
    keptUntil: keptUntil,
    donatedAt: donatedAt,
    createdAt: added,
    updatedAt: added,
  );
}
